import dog from '../assets/dogs.jpg';

// eslint-disable-next-line import/prefer-default-export
export const cards = [
  {
    id: Math.random(),
    img: dog,
    title: 'PsicoCovid',
    categories: 1,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'PsicoCovid',
    categories: 1,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'PsicoCovid',
    categories: 1,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'PsicoCovid',
    categories: 1,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'PsicoCovid',
    categories: 1,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'CulináriaCovid',
    categories: 3,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
  {
    id: Math.random(),
    img: dog,
    title: 'TreinoCovid',
    categories: 2,
    instagram: '@covidx',
    description: 'solução encontrada para combater o Covid-19 da melhor forma possível solução ',
    appleStore: '/',
    googleStore: '/',
    website: '/',
    dataRelease: '30/1/2013',
  },
];
